config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "products#index", as: :authenticated_root
  end

  root 'static_pages#home'
  
  namespace :admin do
    resources :products
    resources :users
    resources :banners
    resources :categories
    resources :user_products, controller: 'orders'
    get '/', to: '/admin/dashboard#index'
    get '/orders', to: 'orders#index'
  end

  post '/webhooks/:source', to: 'webhooks#create'

  post "checkout/create", to: 'checkout#create'
  
  resources :products do
    resources :reviews
    resources :wishlists, only: [:create, :destroy]
  end
  get '/orders', to: 'products#purchased_products', as: 'orders'

  get '/my_wishlists', to: 'wishlists#index', as: 'my_wishlists'
  
  resources :categories

  get '/cart', to: 'cart#show'

  post 'cart/add'
  post 'cart/remove'

  get '/shop', to: 'products#index', as: 'shop'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/home', to: 'static_pages#home', as: 'home'

  get '/success', to: "checkout#success", as: "checkout_success"
  get '/failure', to: "checkout#failure", as: "checkout_failure"

  
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  banner_id  :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_categories_on_banner_id  (banner_id)
#  index_categories_on_user_id    (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (banner_id => banners.id)
#  fk_rails_...  (user_id => users.id)
#
class Category < ApplicationRecord
  # validates the presence of name
  validates_presence_of :name

  # associations
  belongs_to :user
  belongs_to :banner
  has_many :products, dependent: :destroy

  # order categories by id in descending order
  scope :ordered, -> { order(id: :desc) }

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
    before_action :find_category, only: %w[show edit update destroy]
    before_action :authenticate_user!
    before_action :find_banners
 
     def index
         @categories = Category.order(id: :desc).where(["name LIKE ?","%#{params[:search]}%"])
     end
     
     def new
        @category = Category.new
     end
     
     def show
     end
     
     def create
         @category = current_user.categories.build(category_params)
         if @category.save
             respond_to do |format|
                format.html { redirect_to admin_categories_url(@category) }
             end
         else
            render :new, status: :unprocessable_entity
         end
     end
     
     def edit
         
     end
 
     def update
         if @category.update(category_params)
             respond_to do |format|
                format.html { redirect_to admin_category_url(@category) }
             end
         else
             render :edit, status: :unprocessable_entity
         end
     end
 
     def destroy
         if @category.destroy
             respond_to do |format|
                 format.html { redirect_to admin_categories_url }
             end
         end
     end
 
     private
 
         def category_params
             params.require(:category).permit(:name, :banner_id)
         end
 
         def find_category
             @category ||= Category.find(params[:id])
         end

         def find_banners
            @banners = Banner.all.order(:label)
         end
 end
 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category ||= Category.find(params[:id])
    @categories = Category.all
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_admin_category_breadcrumb.html.erb
<div><small><%= link_to "Browse categories", admin_categories_path, class: "me-2 " %> > <span class="ms-2"><%= link_to @category.name, admin_category_path(@category), class: "ms-2 text-decoration-underline" %></small></div>

app/views/admin/categories/_form.html.erb
<%= form_with model: [:admin, category] do |f| %>
    <%= render 'layouts/errors', f: f %>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :name %></strong>
        </div>
            <%= f.text_field :name, autofocus: true, class: "form-control rounded-0" %>
        </div>
    </div>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :banner %></strong>
        </div>

        <% unless f.object.new_record? %>
            <%= f.select :banner_id, Banner.all.pluck(:label, :id), { include_blank: "Select banner", selected: @category.banner.id }, class: "form-control rounded-0" %>
        <% else %>
            <%= f.select :banner_id, Banner.all.pluck(:label, :id), { include_blank: "Select banner" }, class: "form-control rounded-0" %>
        <% end %>
    </div>

    <div class="actions mb-2">
        <%= f.button "Submit", class: "btn btn-dark rounded-0" %>

        <% if f.object.new_record? %>
            <%= link_to "Cancel", admin_categories_path, class: "btn btn-dark rounded-0" %>
        <% else %>
            <%= link_to "Cancel", admin_category_path(@category), class: "btn btn-dark rounded-0" %>
        <% end %>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="container my-3">
    <%= link_to sanitize("&larr; Back to category page"), admin_category_path(@category) %>

    <div class="header pt-2">
        <h1>Edit category</h1>
        <p>Editing <%= @category.name %></p>
    </div>
    <hr>
    <br>
    <div class="form">
        <%= render 'admin/categories/form', category: @category %>
    </div>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, "categories") %>

<div class="container my-3">
    <div class="header pt-2 d-flex justify-content-between">
        <div class="header-info">
            <h1>Categories (<%= Category.count %>)</h1>
            <p>Manage your Categories</p>
        </div>
        <div class="header-link align-self-center">
            <%= link_to new_admin_category_path, class: "btn btn-dark rounded-0" do %>
                <i class="fa-solid fa-plus"></i>
                Add New
            <% end %>
        </div>
    </div>
    <hr>

    <div class="mb-3">
        <%= form_tag admin_categories_path, method: 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: 'Search categories', class: "form-control form-control rounded-0 w-50" %>
          <%#= submit_tag :Search, class: "btn btn-primary btn-sm mt-2" %>
        <% end %>
    </div>

    <div class="table-wrapper table-responsive">
        <table class="table border">
            <thead>
                <tr class="fw-bold tb-header">
                    <th scope="col">Name</th>
                    <th scope="col">Banner</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col" class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category| %>
                    <tr>
                        <td class="fw-bold"><%= link_to category.name, admin_category_path(category) %></td>
                        <td><%= link_to category.banner.label, admin_banner_path(category) %></td>
                        <td><%= category.user.username %></td>
                        <td><%= category.created_at.strftime("%m/%d/%Y") %></td>
                        <td><%= category.updated_at.strftime("%m/%d/%Y") %></td>
                        <td class="text-center"><i class="fa-solid fa-ellipsis"></i></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container my-3">
    <div class="header pt-2">
        <h1>New Category</h1>
        <p>Add a new category item</p>
    </div>
    <hr>
    <br>
    <div class="form">
        <%= render 'admin/categories/form', category: @category %>
    </div>
</div>

app/views/admin/categories/show.html.erb
<div class="container pt-4 pb-5">

    <div class="top-section d-flex justify-content-between">
        <%= render 'admin/categories/admin_category_breadcrumb' %>

        <div class="action-buttons mb-4 text-center">
            <%= link_to edit_admin_category_path(@category), class: "btn btn-dark btn-sm border rounded-0" do %>
                <i class="fa-regular fa-trash-can"></i>
                Edit
            <% end %>

            <%= link_to admin_category_path(@category), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark border btn-sm rounded-0" do %>
                <i class="fa-regular fa-pen-to-square"></i> 
                Delete
            <% end %>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="table-secondary">
                <tr>
                    <th scope="col">Attributes</th>
                    <th scope="col">Values</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            <tr>
                <td><b>ID</b></td>
                <td><%= @category.id %></td>
            </tr>
            <tr>
                <td><b>Label</b></td>
                <td><%= @category.name %></td>
            </tr>
            <tr>
                <td><b>Banner</b></td>
                <td><%= link_to @category.banner.label, admin_banner_path(@category) %></td>
            </tr>
            <tr>
                <td><b>Created by</b></td>
                <td><%= @category.user.username %></td>
            </tr>
            <tr>
                <td><b>Date created</b></td>
                <td><%= @category.created_at.strftime("%m/%d/%Y") %></td>
            </tr>
            <tr>
                <td><b>Last updated</b></td>
                <td><%= @category.updated_at.strftime("%m/%d/%Y") %></td>
            </tr>
        </table>
    </div>
</div>