config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "products#index", as: :authenticated_root
  end

  root 'static_pages#home'
  
  namespace :admin do
    resources :products
    resources :users
    resources :banners
    resources :categories
    resources :user_products, controller: 'orders'
    get '/', to: '/admin/dashboard#index'
    get '/orders', to: 'orders#index'
  end

  post '/webhooks/:source', to: 'webhooks#create'

  post "checkout/create", to: 'checkout#create'
  
  resources :products do
    resources :reviews
    resources :wishlists, only: [:create, :destroy]
  end
  get '/orders', to: 'products#purchased_products', as: 'orders'

  get '/my_wishlists', to: 'wishlists#index', as: 'my_wishlists'
  
  resources :categories

  get '/cart', to: 'cart#show'

  post 'cart/add'
  post 'cart/remove'

  get '/shop', to: 'products#index', as: 'shop'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/home', to: 'static_pages#home', as: 'home'

  get '/success', to: "checkout#success", as: "checkout_success"
  get '/failure', to: "checkout#failure", as: "checkout_failure"

  
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id             :bigint           not null, primary key
#  archive        :boolean          default(FALSE)
#  average_rating :decimal(, )      default(0.0)
#  code           :string
#  description    :text
#  feature        :boolean          default(FALSE)
#  name           :string
#  reviews_count  :integer          default(0)
#  sales_count    :integer          default(0)
#  stock          :integer
#  unit_price     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  category_id    :bigint           not null
#  user_id        :bigint           not null
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#  index_products_on_name         (name) UNIQUE
#  index_products_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Product < ApplicationRecord
    # validates presence of user
    validates :user_id, :category_id, presence: true

    # validates presence and uniqueness of name
    validates :name, presence: true, uniqueness: { case_sensitive: false, message: "Product name must be unique" }

    # validates numericality of stock which must be integer
    validates :stock, presence: true, numericality: { only_integer: true, greater_than: 0 }

    # validates numericality of unit_price which must be integer
    validates :unit_price, presence: true, numericality: { greater_than: 0 }

    # create product code before saving to database
    before_create :product_code
    
    # associations
    belongs_to :user
    belongs_to :category

    has_many :reviews, dependent: :destroy
    has_many :wishlists, dependent: :destroy
    has_many :wishlist_users, through: :wishlists, source: :user
    has_many :orderables, dependent: :destroy
    has_many :carts, through: :orderables, dependent: :destroy
    has_many :user_products, dependent: :destroy
    has_many :buyers, through: :user_products, dependent: :destroy, source: :user

    # order products by id
    scope :ordered, -> { order(id: :desc) }

    # display six products per page
    paginates_per 6

    # active storage image and validations
    has_one_attached :image do |attachable|
        attachable.variant :display, resize_to_limit: [500, 500]
    end

    validates :image,   content_type: { in: %w[image/jpeg image/png],
                                      message: "must be a valid image format (jpg/png)" },
                      size:         { less_than: 1.megabytes,
                                      message:   "should be less than 1MB" }

    def Product.new_token
        SecureRandom.urlsafe_base64(4)
    end
    
    def product_code
        self.code = Product.new_token
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
    before_action :find_product, only: %w[show edit update destroy]
    before_action :authenticate_user!
    before_action :find_categories
    # before_action :find_category, only: :show

    def index
        @products = Product.order(id: :desc).where(["name LIKE ?","%#{params[:search]}%"]).includes(:user).page(params[:page])
    end
    
    def new
       @product = Product.new
    end
    
    def show
    end
    
    def create
        @product = current_user.products.build(product_params)
        if @product.save
            respond_to do |format|
                format.html { redirect_to admin_products_url(@product), notice: "Product created." }
            end
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    def edit
        
    end

    def update
        if @product.update(product_params)
            respond_to do |format|
                format.html { redirect_to admin_product_url(@product), notice: "Product updated." }
            end
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        if @product.destroy
            respond_to do |format|
                format.html { redirect_to admin_products_url, notice: "Product destroyed." }
            end
        end
    end

    private

        def product_params
            params.require(:product).permit(:name, :description, :unit_price, :code, :stock, :image, :feature, :archive, :category_id)
        end

        def find_product
            @product ||= Product.find(params[:id])
        end

        def find_categories
            @categories = Category.all.order(:name)
        end

        def find_category
            @category ||= @product.category.find(params[:category_id])
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_categories, only: %w[index show]

    def index
        @products = Product.ordered.where(archive: false).page(params[:page])
    end

    def show
        @product ||= Product.find(params[:id])
        # @products = Product.all.take(3)
        @reviews = @product.reviews.includes(:user)
        @related_products = @product.category.products.where.not(id: @product).limit(3)
    end

    def purchased_products
        @products = current_user.purchased_products
    end

    private

        def set_categories
            @categories = Category.all
        end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_admin_product_breadcrumb.html.erb
<div><small><%= link_to "Browse products", admin_products_path, class: "me-2 " %> > <%= link_to "Small chops", '#', class: "mx-2" %> > <span class="ms-2"><%= link_to @product.name, admin_product_path(@product), class: "ms-2 text-decoration-underline" %></small></div>

app/views/admin/products/_form.html.erb
<%= form_with model: [:admin, product] do |f| %>
    <%= render 'layouts/errors', f: f %>

    <div class="row mb-3">
        <div class="col-md-6">
            <%= f.label :name, class: "fw-bold mb-3 mb-3" %>
            <%= f.text_field :name, class: "form-control rounded-0" %>
        </div>

        <div class="col-md-6">
            <%= f.label :description, class: "fw-bold mb-3" %>
            <%= f.text_area :description, class: "form-control rounded-0", rows: 3 %>
        </div>
    </div>

    <br>

    <div class="row">
        <div class="col-md-3">
            <div class="mb-3">
                <strong><%= f.label :images, class: "mb-3" %></strong>
                <%= f.file_field :image, class: "form-control" %>
            </div>
        </div>
        <div class="col-md-3 mb-3">
            <%= f.label :stock, class: "fw-bold mb-3" %>
            <%= f.text_field :stock, class: "form-control rounded-0" %>
        </div>

        <div class="col-md-3 mb-3">
            <%= f.label :price, class: "fw-bold mb-3" %>
            <%= f.number_field :unit_price, class: "form-control rounded-0" %>
        </div>

        <div class="col-md-3 mb-3">
            <%= f.label :category, class: "fw-bold mb-3" %>
            <% unless f.object.new_record? %>
                <%= f.select :category_id, Category.all.pluck(:name, :id), { include_blank: "Select category", selected: @product.category.id }, class: "form-control rounded-0" %>
            <% else %>
                <%= f.select :category_id, Category.all.pluck(:name, :id), { include_blank: "Select category" }, class: "form-control rounded-0" %>
            <% end %>
        </div>

        <div class="col-md-3 mb-3">
            <div class="feature-box border pt-2 d-flex justify-content-between">
                <%= f.check_box :feature, class: "form-check-input mx-2" %> 
                <div class="featured-label">
                    <strong><%= f.label :feature %></strong>
                    <p><small>
                        This product will appear anywhere in the homepage.
                    </small></p>
                </div>
            </div>
        </div>

        <div class="col-md-3 mb-3">
            <div class="feature-box border pt-2 d-flex justify-content-between">
                <%= f.check_box :archive, class: "form-check-input mx-2" %> 
                <div class="archived-label">
                    <strong><%= f.label :archive %></strong>
                    <p><small>
                        This product will not appear anywhere in the store.
                    </small></p>
                </div>
            </div>
        </div>

        <div class="col-md-3 mb-3">
            <% if product.image.attached? %>
                <%= image_tag product.image, data: { previews_target: "preview" }, class: "img-fluid mb-3" %>
            <% else %>
                <%= image_tag "", data: { previews_target: "preview" }, class: "img-fluid mb-3" %>
            <% end %>
        </div>
    </div>

    <div class="actions mb-2">
        <%= f.button "Submit", class: "btn btn-dark rounded-0" %>

        <% if !(f.object.new_record?) %>
            <%= link_to "Cancel", admin_product_path(@product), class: "btn btn-dark rounded-0" %>
        <% else %>
            <%= link_to "Cancel", admin_products_path, class: "btn btn-dark rounded-0" %>
        <% end %>
    </div>
<% end %>

app/views/admin/products/edit.html.erb
<div class="container my-3">
    <%= link_to sanitize("&larr; Back to product page"), admin_product_path(@product) %>

    <div class="header pt-2">
        <h1>Edit Product</h1>
        <p>Editing <%= @product.name %></p>
    </div>
    <hr>
    <br>
    <div class="form">
        <%= render 'admin/products/form', product: @product %>
    </div>
</div>

app/views/admin/products/index.html.erb
<% provide(:title, "Products") %>

<div class="container my-3">
    <div class="header pt-2 d-flex justify-content-between">
        <div class="header-info">
            <h1>Products (<%= Product.count %>)</h1>
            <p>Manage your products</p>
        </div>
        <div class="header-link align-self-center">
            <%= link_to new_admin_product_path, class: "btn btn-dark rounded-0" do %>
                <i class="fa-solid fa-plus"></i>
                Add New
            <% end %>
        </div>
    </div>
    <hr>

    <div class="mb-3">
        <%= form_tag admin_products_path, method: 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: 'Search products', class: "form-control form-control rounded-0 w-50" %>
          <%#= submit_tag :Search, class: "btn btn-primary btn-sm mt-2" %>
        <% end %>
    </div>

    <div class="table-wrapper table-responsive">
        <table class="table border">
            <thead>
                <tr class="fw-bold tb-header">
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Image</th>
                    <th scope="col">Archived</th>
                    <th scope="col">Featured</th>
                    <th scope="col">Category</th>
                    <th scope="col">Price</th>
                    <th scope="col">Code</th>
                    <th scope="col">Stock</th>
                    <th scope="col">Date</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @products.each do |product| %>
                    <tr>
                        <td class="fw-bold"><%= link_to product.name, admin_product_path(product) %></td>
                        <td ><%= simple_format(product.description.truncate(50)) %></td>
                        <td>
                            <% if product.image.attached? %>
                                <%= image_tag product.image, size: "100x80" %>
                            <% else %>
                                <%= image_tag 'food-3.jpg', size: "100x80" %>
                            <% end %>
                        </td>
                        <td><%= product.archive %></td>
                        <td><%= product.feature %></td>
                        <td><%= link_to product.category.name, admin_category_path(product.category) %></td>
                        <td><%= number_to_currency(product.unit_price, unit: "₦") %></td>
                        <td><%= product.code %></td>
                        <td><%= product.stock %></td>
                        <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
                        <td class="text-center"><i class="fa-solid fa-ellipsis"></i></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
        <div class="mt-3 text-end">
    
            <%= paginate @products, window: 2, theme: 'bootstrap-5',
                            pagination_class: "pagination-sm flex-wrap justify-content-center",
                            nav_class: "d-inline-block" %>
        </div>
    </div>
</div>

app/views/admin/products/new.html.erb
<div class="container my-3">
    <div class="header pt-2">
        <h1>New Product</h1>
        <p>Add a new product item</p>
    </div>
    <hr>
    <br>
    <div class="form">
        <%= render 'admin/products/form', product: @product %>
    </div>
</div>

app/views/admin/products/show.html.erb
<div class="container pt-4 pb-5">

    <div class="top-section d-flex justify-content-between">
        <%= render 'admin/products/admin_product_breadcrumb' %>

        <div class="action-buttons mb-4 text-center">
            <%= link_to edit_admin_product_path(@product), class: "btn btn-dark btn-sm border rounded-0" do %>
                <i class="fa-regular fa-trash-can"></i>
                Edit
            <% end %>

            <%= link_to admin_product_path(@product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark border btn-sm rounded-0" do %>
                <i class="fa-regular fa-pen-to-square"></i> 
                Delete
            <% end %>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="table-secondary">
                <tr>
                    <th scope="col">Attributes</th>
                    <th scope="col">Values</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            <tr>
                <td><b>ID</b></td>
                <td><%= @product.id %></td>
            </tr>
            <tr>
                <td><b>Name</b></td>
                <td><%= @product.name %></td>
            </tr>
            <tr>
                <td><b>Category</b></td>
                <td><%= @product.category.name %></td>
            </tr>
            <tr>
                <td><b>Description</b></td>
                <td><%= @product.description %></td>
            </tr>
            <tr>
                <td><b>Image</b></td>
                <td>
                    <% if @product.image.attached? %>
                        <%= image_tag(@product.image, class: "w-25") %>
                    <% else %>
                        <%= image_tag 'food-3.jpg', class: "w-25" %>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td><b>Unit Price</b></td>
                <td><%= number_to_currency(@product.unit_price, unit: "₦") %></td>
            </tr>
            <tr>
                <td><b>Code</b></td>
                <td><%= @product.code %></td>
            </tr>
            <tr>
                <td><b>Featured?</b></td>
                <td><%= @product.feature %></td>
            </tr>
            <tr>
                <td><b>Archived?</b></td>
                <td><%= @product.archive %></td>
            </tr>
            <tr>
                <td><b>Created by</b></td>
                <td><%= @product.user.username %></td>
            </tr>
            <tr>
                <td><b>Date created</b></td>
                <td><%= @product.created_at.strftime("%m/%d/%Y") %></td>
            </tr>
            <tr>
                <td><b>Last updated</b></td>
                <td><%= @product.updated_at.strftime("%m/%d/%Y") %></td>
            </tr>
        </table>
    </div>
</div>