config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "products#index", as: :authenticated_root
  end

  root 'static_pages#home'
  
  namespace :admin do
    resources :products
    resources :users
    resources :banners
    resources :categories
    resources :user_products, controller: 'orders'
    get '/', to: '/admin/dashboard#index'
    get '/orders', to: 'orders#index'
  end

  post '/webhooks/:source', to: 'webhooks#create'

  post "checkout/create", to: 'checkout#create'
  
  resources :products do
    resources :reviews
    resources :wishlists, only: [:create, :destroy]
  end
  get '/orders', to: 'products#purchased_products', as: 'orders'

  get '/my_wishlists', to: 'wishlists#index', as: 'my_wishlists'
  
  resources :categories

  get '/cart', to: 'cart#show'

  post 'cart/add'
  post 'cart/remove'

  get '/shop', to: 'products#index', as: 'shop'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/home', to: 'static_pages#home', as: 'home'

  get '/success', to: "checkout#success", as: "checkout_success"
  get '/failure', to: "checkout#failure", as: "checkout_failure"

  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  address_line_1         :string
#  address_line_2         :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  phone_number           :string           not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  reviews_count          :integer          default(0)
#  role                   :integer          default("Normal"), not null
#  surname                :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  paystack_customer_id   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_paystack_customer_id  (paystack_customer_id) UNIQUE
#  index_users_on_phone_number          (phone_number)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #  validates the presence, uniqueness and case sensitivity of username
  validates :username, presence: true, uniqueness: { case_sensitive: false, message: "Username must be unique" }

  # validates presence of first name, surname and address line attributes
  validates_presence_of :first_name, :surname, :address_line_1

  def name
    "#{first_name}  #{surname}"
  end

  # associations
  has_many :products, dependent: :destroy
  has_many :banners, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :wishlisted_products, through: :wishlists, source: :product
  has_many :user_products, dependent: :destroy
  has_many :purchased_products, through: :user_products, dependent: :destroy, source: :product

  # active storage image and validations
  has_one_attached :avatar do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end

  validates :avatar, content_type: { in: %w[image/jpeg image/png],
                                    message: "must be a valid image format" },
                    size:         { less_than: 1.megabytes,
                                    message:   "should be less than 1MB" }

  # roles for authorizations
  enum :role, { 
    'Normal': 0,
    'Super Admin': 1,
    'Admin': 2
   }

  #  creates a new paystack customer id after the user object is created and updates it in the database
   after_create do
    return if paystack_customer_id.present?

    paystack_customers = PaystackCustomers.new(PAYSTACKOBJ)

    customer = paystack_customers.create(
                                        email: email ,
                                        first_name: first_name,
                                        last_name: surname,
                                        phone: phone_number
                                       )

    update(paystack_customer_id: customer['data']['customer_code'])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    before_action :find_user, only: %w[show edit update destroy]
    
    def index
        @users = User.order(id: :desc).where(["username LIKE ?","%#{params[:search]}%"])
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            respond_to do |format|
                format.html { redirect_to admin_user_url(@user), notice: "User created." }
            end
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        
    end

    def update
        if @user.update(user_params)
            respond_to do |format|
                format.html { redirect_to admin_user_url(@user), notice: "User updated." }
            end
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        if @user.destroy
            respond_to do |format|
                format.html { redirect_to admin_users_url, notice: "User deleted."}
            end
        end
    end

    private

        def user_params
            params.require(:user).permit(:first_name, :surname, :email, :address_line_1, :address_line_2, :role, :username)
        end

        def find_user
            @user ||= User.find(params[:id])
        end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_admin_user_breadcrumb.html.erb
<div><small><%= link_to "Browse users", admin_users_path, class: "me-2 " %> > <%= link_to @user.username, admin_user_path(@user), class: "ms-2 text-decoration-underline" %></small></div>

app/views/admin/users/_form.html.erb
<%= form_with model: [:admin, user] do |f| %>
    <%= render 'layouts/errors', f: f %>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :email %></strong>
        </div>
            <%= f.email_field :email, autofocus: true, placeholder: "hello@example.com", autocomplete: "email", class: "form-control form-control-lg rounded-0" %>
    </div>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :username %></strong>
        </div>
        <%= f.text_field :username, placeholder: "Enter username", autocomplete: true, class: "form-control form-control-lg rounded-0" %>
    </div>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :first_name %></strong>
        </div>
        <%= f.text_field :first_name, placeholder: "Enter your first name", autocomplete: true, class: "form-control form-control-lg rounded-0" %>
    </div>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :surname %></strong>
        </div>
        <%= f.text_field :surname, placeholder: "Enter your surname", autocomplete: true, class: "form-control form-control-lg rounded-0" %>
    </div>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :address_line_1 %></strong>
        </div>
        <%= f.text_field :address_line_1, placeholder: "Enter your address", autocomplete: true, class: "form-control form-control-lg rounded-0" %>
    </div>

    <div class="mb-3">
        <div class="mb-1">
            <strong><%= f.label :role %></strong>
        </div>
        <%= f.select :role, User.roles.keys, { include_blank: true }, class: "form-control form-control-lg rounded-0 form-select" %>
    </div>

    <div class="actions mb-2">
        <%= f.button "Submit", class: "btn btn-dark rounded-0" %>
            <%# if f.object.new_record? %>
                <!--<span class="show-when-enabled">Create user</span>
                <span class="show-when-disabled"><i class="fa-solid fa-spinner fa-spin text-white"></i> Creating user...</span> -->
            <%# else %>
                <!--<span class="show-when-enabled">Update user</span>
                <span class="show-when-disabled"><i class="fa-solid fa-spinner fa-spin text-white"></i> Updating user...</span>-->
            <%# end %>
        <%# end %>

        <% if f.object.new_record? %>
            <%= link_to "Cancel", admin_users_path, class: "btn btn-dark rounded-0" %>
        <% else %>
            <%= link_to "Cancel", admin_user_path(@user), class: "btn btn-dark rounded-0" %>
        <% end %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container my-3">
    <%= link_to sanitize("&larr; Back to user page"), admin_user_path(@user) %>

    <div class="header pt-2">
        <h1>Edit User</h1>
        <p>Editing <%= @user.username %></p>
    </div>
    <hr>
    <br>
    <div class="form">
        <%= render 'admin/users/form', user: @user %>
    </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, "Customers") %>

<div class="container my-3">
    <div class="header pt-2 d-flex justify-content-between">
        <div class="header-info">
            <h1>Users (<%= User.count %>)</h1>
            <p>Manage your users</p>
        </div>
        <div class="header-link align-self-center">
            <%= link_to new_admin_user_path, class: "btn btn-dark rounded-0" do %>
                <i class="fa-solid fa-plus"></i>
                Add New
            <% end %>
        </div>
    </div>
    <hr>

    <div class="mb-3">
        <%= form_tag admin_users_path, method: 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: 'Search users', class: "form-control form-control rounded-0 w-50" %>
          <%#= submit_tag :Search, class: "btn btn-primary btn-sm mt-2" %>
        <% end %>
    </div>

    <div class="table-wrapper table-responsive">
        <table class="table border">
            <thead>
                <tr class="fw-bold tb-header">
                    <th scope="col">First name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Email</th>
                    <th scope="col">Paystack customer id</th>
                    <th scope="col">Username</th>
                    <th scope="col">Role</th>
                    <th scope="col">Address</th>
                    <th scope="col">Created</th>
                    <th scope="col">Updated</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td class="fw-bold"><%= link_to user.first_name, admin_user_path(user) %></td>
                        <td ><%= user.surname %></td>
                        <td><%= user.email %></td>
                        <td><%= user.paystack_customer_id if user.paystack_customer_id.present? %></td>
                        <td><%= user.username %></td>
                        <td><%= user.role %></td>
                        <td><%= user.address_line_1 %></td>
                        <td><%= user.created_at.strftime("%m/%d/%Y") %></td>
                        <td><%= user.updated_at.strftime("%m/%d/%Y") %></td>
                        <td class="text-center"><i class="fa-solid fa-ellipsis"></i></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin/users/new.html.erb
<div class="container my-3">
    <div class="header pt-2">
        <h1>New User</h1>
        <p>Add a new user</p>
    </div>
    <hr>
    <br>
    <div class="form">
        <%= render 'admin/users/form', user: @user %>
    </div>
</div>

app/views/admin/users/show.html.erb
<div class="container pt-4 pb-5">

    <div class="top-section d-flex justify-content-between">
        <%= render 'admin/users/admin_user_breadcrumb' %>

        <div class="action-buttons mb-4 text-center">
            <%= link_to edit_admin_user_path(@user), class: "btn btn-dark btn-sm border rounded-0" do %>
                <i class="fa-regular fa-trash-can"></i>
                Edit
            <% end %>

            <%= link_to admin_user_path(@user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-dark border btn-sm rounded-0" do %>
                <i class="fa-regular fa-pen-to-square"></i> 
                Delete
            <% end %>
        </div>
    </div>

    <h1 class="mb-4"><%= @user.name %></h1>

    <div class="row">
        <div class="col-md-6">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead class="table-secondary">
                        <tr>
                            <th scope="col">Attributes</th>
                            <th scope="col">Values</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                    <tr>
                        <td><b>ID</b></td>
                        <td><%= @user.id %></td>
                    </tr>
                    </tbody>
                    <tr>
                        <td><b>Paystack Customer ID</b></td>
                        <td><%= @user.paystack_customer_id if @user.paystack_customer_id.present? %></td>
                    </tr>
                    <tr>
                        <td><b>First name</b></td>
                        <td><%= @user.first_name %></td>
                    </tr>
                    <tr>
                        <td><b>Surname</b></td>
                        <td><%= @user.surname %></td>
                    </tr>
                    </tr>
                    <tr>
                        <td><b>Username</b></td>
                        <td><%= @user.username %></td>
                    </tr>
                    <tr>
                        <td><b>Email Address</b></td>
                        <td><%= @user.email %></td>
                    </tr>
                    <tr>
                        <td><b>Role</b></td>
                        <td><%= @user.role %></td>
                    </tr>
                    <tr>
                        <td><b>Phone number</b></td>
                        <td><%= @user.phone_number %></td>
                    </tr>
                    <tr>
                        <td><b>Address Line 1</b></td>
                        <td><%= @user.address_line_1 %></td>
                    </tr>
                    </tr>
                    <tr>
                        <td><b>Address Line 2</b></td>
                        <td><%= @user.address_line_2 %></td>
                    </tr>
                    </tr>
                    <tr>
                        <td><b>Date created</b></td>
                        <td><%= @user.created_at.strftime("%m/%d/%Y") %></td>
                    </tr>
                    </tr>
                    <tr>
                        <td><b>Last updated</b></td>
                        <td><%= @user.updated_at.strftime("%m/%d/%Y") %></td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="col-md-6">
            <h4>Purchased Products</h4>
            <div class="table-wrapper table-responsive">
                <table class="table border">
                    <thead>
                        <tr class="fw-bold tb-header">
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Date purchased</th>
                            <th scope="col" class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @user.user_products.each do |user_product| %>
                            <% product = user_product.product %>
                            <tr>
                                <td><%= link_to product.name, product %></td>
                                <td><%= link_to number_to_currency(product.unit_price, unit: "₦"), product %></td>
                                <td><%= user_product.created_at.strftime("%m/%d/%Y") %></td>
                                <td class="text-center"><i class="fa-solid fa-ellipsis"></i></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>